


export const CourseData = [
  {
    id: 1,
    image: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses1.jpg",
    price: "27.00",
    level: "Beginner",
    ratings: "(4.5 ratings)",
    title: "Introduction to Digital Marketing",
    smallImage: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses-user1.jpg",
    name: "Prof.Donnie Ball",
    students: "70+ students",
  },
  {
    id: 2,
    image: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses2.jpg",
    price: "27.00",
    level: "Beginner",
    ratings: "(4.5 ratings)",
    title: "Increasing Engagement with Instagram",
    smallImage: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses-user1.jpg",
    name: "Prof.Donnie Ball",
    students: "70+ students",
  },
  {
    id: 3,
    image: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses3.jpg",
    price: "27.00",
    level: "Beginner",
    ratings: "(4.5 ratings)",
    title: "Full Stack Web Development Bootcamp",
    smallImage: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses-user1.jpg",
    name: "Prof.Donnie Ball",
    students: "70+ students",
  },
  {
    id: 4,
    image: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses4.jpg",
    price: "27.00",
    level: "Beginner",
    ratings: "(4.5 ratings)",
    title: "Introduction to Digital Marketing",
    smallImage: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses-user1.jpg",
    name: "Prof.Donnie Ball",
    students: "70+ students",
  },
  {
    id: 5,
    image: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses5.jpg",
    price: "27.00",
    level: "Beginner",
    ratings: "(4.5 ratings)",
    title: "Python Programming for Beginners",
    smallImage: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses-user1.jpg",
    name: "Prof.Donnie Ball",
    students: "70+ students",
  },
  {
    id: 6,
    image: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses6.jpg",
    price: "27.00",
    level: "Beginner",
    ratings: "(4.5 ratings)",
    title: "Graphic Design Mastery: From Concept to Creation",
    smallImage: "https://demo.themeies.com/edugen/wp-content/uploads/2024/09/courses-user1.jpg",
    name: "Prof.Donnie Ball",
    students: "70+ students",
  },
]

